language: minimal

addons:
  apt:
    packages:
      - python-pygments

install:
  - curl --silent -L https://github.com/gohugoio/hugo/releases/download/v0.76.5/hugo_0.76.5_Linux-64bit.tar.gz | tar zxf -

script:
  - ./hugo --cleanDestinationDir

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: public
  repo: octavian-h/personal-site
  target_branch: gh-pages
  fqdn: www.hasna.ro
  on:
    branch: master
