baseurl = "https://www.hasna.ro/"
languageCode = "ro"
title = "Octavian Hasna"
# Enable comments by entering your Disqus shortname
disqusShortname = ""
# Enable Google Analytics by entering your tracking code
googleAnalytics = ""
theme = "hugo-sustain"

[permalinks]
  post = "/:year-:month-:day-:slug"

[params]
  avatar = "profile.png"
  author = "Octavian Hasna"
  description = "Website de prezentare a proiectelor personale si un blog cu de toate."

  # Custom assets can be linked with their paths relative to static/
  custom_css = []
  custom_js  = []

[params.social]
  Github        = "octavian-h"
  Email         = "octavian@hasna.ro"
  LinkedIn      = "octavian-lucian-hasna-9aaa85105"

## Main Menu
[[menu.main]]
  name = "blog"
  weight = 100
  identifier = "blog"
  url = "/blog/"
[[menu.main]]
  name = "projects"
  weight = 200
  identifier = "projects"  
  url = "/projects/"
