baseURL: https://www.hasna.ro/
title: Octavian Hasna
paginate: 5
theme: hugo-PaperMod

enableRobotsTXT: true
enableGitInfo: true
googleAnalytics: G-0YE02LQLLW
disqusShortname: octavian1001

taxonomies:
  category: categories
  tag: tags

defaultContentLanguage: en
languages:
  en:
    languageName: English
    contentDir: content/en
    weight: 1
    params:
      label:
        text: Home
    menu:
      main:
        - name: Projects
          url: /projects/
          weight: 2
        - name: Research
          url: /research/
          weight: 3          
        - name: Publications
          url: /publications/
          weight: 4

  ro:
    languageName: Română
    contentDir: content/ro
    weight: 2
    params:
      label:
        text: Acasa
    menu:
      main:
        - name: Blog
          url: /posts/
          weight: 1

minify:
  minifyOutput: true

params:
  env: production
  author: Octavian Hasna
  description: Presentation website with personal projects, research interests, publications and a blog with Romanian posts.

  ShowReadingTime: false
  ShowShareButtons: false
  ShowBreadCrumbs: false
  ShowToc: true
  comments: false
  defaultTheme: auto
  disableThemeToggle: false
  disableSpecial1stPost: true

  assets:
    favicon: /favicon.ico

  profileMode:
    enabled: true
    imageUrl: /apple-touch-icon.png
    imageTitle: site logo

  socialIcons:
    - name: github
      url: https://github.com/octavian-h
    - name: linkedin
      url: https://ro.linkedin.com/in/octavian-lucian-hasna-9aaa85105
    - name: stackoverflow
      url: https://stackoverflow.com/users/2607910/octavian1001

privacy:
  disqus:
    disable: true
  googleAnalytics:
    anonymizeIP: false
    disable: false
    respectDoNotTrack: true
    useSessionStorage: false
  instagram:
    disable: true
  twitter:
    disable: true
  vimeo:
    disable: true
  youtube:
    disable: false
    privacyEnhanced: true
